# Generated by Django 5.2 on 2025-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('spin_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
